# Generated by Django 3.1.6 on 2021-02-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Miranda', max_length=50),
            preserve_default=False,
        ),
    ]
