# Generated by Django 3.1.6 on 2021-02-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210202_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.CharField(blank=True, max_length=15, verbose_name='What gardening zone are you in?'),
        ),
    ]
