# Generated by Django 3.1.6 on 2021-02-03 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20210203_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100, verbose_name='Scientific Name, if applicable')),
                ('kind', models.CharField(choices=[('V', 'Vegetable'), ('FR', 'Fruit'), ('H', 'Herb'), ('FL', 'Flower')], default='V', max_length=2)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
