# Generated by Django 3.1.6 on 2021-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='kind',
            field=models.CharField(choices=[('chamomile.png', 'Flower'), ('mint.png', 'Herb')], default='chamomile.png', max_length=500),
        ),
    ]
