# Generated by Django 3.1.6 on 2021-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210204_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='seed',
            name='kind',
            field=models.CharField(choices=[('FLOWER', 'Flower'), ('HERB', 'Herb')], default='FLOWER', max_length=500),
        ),
    ]
