# Generated by Django 3.1.6 on 2021-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210205_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='seed',
            name='seed_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seed Source'),
        ),
    ]
