# Generated by Django 3.1.6 on 2021-02-08 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210208_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='seed',
            name='kind',
            field=models.CharField(choices=[('Flower', 'Flower'), ('Herb', 'Herb'), ('Arugula', 'Arugula'), ('Asparagus', 'Asparagus'), ('Basil', 'Basil'), ('Beet', 'Beet'), ('Broccoli', 'Broccoli'), ('Brussels', 'Brussels'), ('Cabbage(green)', 'Cabbage(green)'), ('Cabbage(red)', 'Cabbage(red)'), ('Calendula', 'Calendula'), ('Carrots', 'Carrots'), ('Cauliflower', 'Cauliflower'), ('Corn', 'Corn'), ('Cucumber', 'Cucumber'), ('Daikon', 'Daikon'), ('Dill', 'Dill'), ('Eggplant', 'Eggplant'), ('Fennel', 'Fennel'), ('Garlic', 'Garlic'), ('Kale', 'Kale'), ('Lettuce', 'Lettuce'), ('Mint', 'Mint'), ('Onion', 'Onion'), ('Oregano', 'Oregano'), ('Parsley', 'Parsley'), ('Peas', 'Peas'), ('Pepper(hot)', 'Pepper(hot)'), ('Pepper(bell)', 'Pepper(bell)'), ('Potato', 'Potato'), ('Pumpkin', 'Pumpkin'), ('Radish', 'Radish'), ('Spinach', 'Spinach'), ('Tarragon', 'Tarragon'), ('Thyme', 'Thyme'), ('Tomato', 'Tomato'), ('Tomato(cherry)', 'Tomato(cherry)'), ('Tomato(heirloom)', 'Tomato(heirloom)'), ('Beans(green)', 'Beans(green)'), ('Bokchoy)', 'Bokchoy'), ('Chives', 'Chives'), ('Collards', 'Collards'), ('Delicata', 'Delicata'), ('Eggplant(graffiti)', 'Eggplant(graffiti'), ('Jalapeno', 'Jalapeno'), ('Peas(snow)', 'Peas(snow)'), ('Rhubarb', 'Rhubarb'), ('Sage', 'Sage'), ('Scallions', 'Scallions'), ('Squash(acorn)', 'Squash(acorn)'), ('Squash(butternut)', 'Squash(butternut'), ('Squash(summer)', 'Squash(summer)'), ('Turnip', 'Turnip'), ('Yam', 'Yam'), ('Blueberries', 'Blueberries'), ('Cantaloupe', 'Cantaloupe'), ('Flower(other)', 'Flower(other)'), ('Fruit(other)', 'Fruit(other)'), ('Raspberries', 'Raspberries'), ('Strawberries', 'Strawberries'), ('Watermelon', 'Watermelon'), ('Veggie(other)', 'Veggie(other)')], default='Flower', max_length=500),
        ),
    ]
