# Generated by Django 3.1.6 on 2021-02-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210208_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.seed'),
        ),
    ]
