# Generated by Django 3.1.6 on 2021-02-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210209_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='seeds',
            field=models.ManyToManyField(to='main_app.Seed'),
        ),
    ]
