# Generated by Django 3.1.6 on 2021-02-09 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_garden_seeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='grow_directions',
            field=models.TextField(blank=True, max_length=500, verbose_name='Growing Directions'),
        ),
        migrations.AddField(
            model_name='seed',
            name='maturity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Days to Maturity'),
        ),
        migrations.AddField(
            model_name='seed',
            name='spacing',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plant Spacing'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
