# Generated by Django 3.1.6 on 2021-02-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210209_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('beet', 'beet'), ('cabbage(green)', 'cabbage(green)'), ('calendula', 'calendula'), ('radish', 'radish'), ('scallions', 'scallions'), ('strawberries', 'strawberries'), ('tomato(heirloom)', 'tomato(heirloom)')], default='beet', max_length=500),
        ),
    ]
