# Generated by Django 3.1.6 on 2021-02-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20210209_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500, verbose_name='Your Message'),
        ),
    ]
