# Generated by Django 3.1.6 on 2021-02-10 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20210209_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
